name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update -y
        sudo dpkg --add-architecture i386 && sudo apt-get update -y
        sudo apt-get install -y dpkg fakeroot wine32 wine64 rpm nasm make genisoimage coreutils dosfstools
        chmod +x ./buildunix.sh

    - name: Generate builds
      run: |
        sudo ./buildunix.sh

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: disk_images
        path: disk_images/
